export const storeProducts = [
    {
        id: 1,
        name:"Zebra Plant",
        img: "./img/zebra_plant.jpg",
        price: 80,
        size: "XS",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq: "3'' pot"
    },
    {
        id: 2,
        name: "assorted succulent",
        img: "./img/succulent.jpg",
        price: 95,
        size: "XS",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq:"3'' pot"
    },
    {
        id: 3,
        name: "assorted cactus",
        img: "./img/cactus.jpg",
        price: 35,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq:"4'' pot"
    },
    {
        id: 4,
        name: "chinese money plant",
        img: "./img/chinese_money.jpg",
        price: 95,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq:"4'' pot"
    },
    {
        id: 5,
        name: "bella palm",
        img: "./img/parlor_palm.jpg",
        price: 105,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bring light would be ideal",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq:"4'' pot"
    },
    {
        id: 6,
        name:"spider plant",
        img: "./img/spider_plant.jpg",
        price: 60,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bright light would be ideal",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq: "6'' pot"
    },
    {
        id: 7,
        name:"pears and jade",
        img: "./img/pearls_and_jade.jpg",
        price: 55,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bright light would be ideal",
        waterReq: "1 x one week",
        pet: "no",
        pottingReq: "6'' pot"
},
{
        id: 8,
        name:"stromanthe",
        img: "./img/stromanthe.jpg",
        price: 60,
        size: "MD",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x one week",
        pet: "yes",
        pottingReq: "6'' pot"
}
    // {
    //     id: 7,
    //     name: "CORDYLINE",
    //     img: "./img/plant.jpg",
    //     price: 70,
    //     info: "Small and pretty",
    //     inCart: false,
    //     count: 0,
    //     total: 0
    // },
    // {
    //     id: 8,
    //     name: "DARCENA MARG STAG",
    //     img: "./img/plant.jpg",
    //     price: 90,
    //     info: "Great house plant!",
    //     inCart: false,
    //     count: 0,
    //     total: 0
    // }
];

export const detailProduct = {
    _id:"5d0f72aa0f66b75f1b55960e",
    name:"zebra plant",
    img: "./img/zebra_plant.jpg",
    price: 80,
    size: "xs",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "bright",
    waterReq: "1 x three weeks",
    pet: "no",
    pottingReq: "3'' pot"
};