export const storeProducts = [
    {
        id: 1,
        name:"Zebra Plant",
        img: "img/zebra_plant.JPG",
        price: 80,
        size: "XS",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq: "3'' pot"
    },
    {
        id: 2,
        name: "Assorted Succulent",
        img: "img/succulent.JPG",
        price: 95,
        size: "XS",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq:"3'' pot"
    },
    {
        id: 3,
        name: "Assorted Cactus",
        img: "img/cactus.JPG",
        price: 35,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "no",
        pottingReq:"4'' pot"
    },
    {
        id: 4,
        name: "Chinese Money Plant",
        img: "img/chinese_money.JPG",
        price: 95,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq:"4'' pot"
    },
    {
        id: 5,
        name: "Bella Palm",
        img: "img/parlor_palm.JPG",
        price: 105,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bring light would be ideal",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq:"4'' pot"
    },
    {
        id: 6,
        name:"Spider Plant",
        img: "img/spider_plant.JPG",
        price: 60,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bright light would be ideal",
        waterReq: "1 x three weeks",
        pet: "yes",
        pottingReq: "6'' pot"
    },
    {
        id: 7,
        name:"Pears and Jade",
        img: "img/pearls_and_jade.JPG",
        price: 55,
        size: "S",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "medium to bright light would be ideal",
        waterReq: "1 x one week",
        pet: "no",
        pottingReq: "6'' pot"
},
{
        id: 8,
        name:"Stromanthe",
        img: "img/stromanthe.JPG",
        price: 60,
        size: "MD",
        inCart: false,
        count: 3,
        total: 0,
        userID: "",
        lightReq: "bright light is recommended",
        waterReq: "1 x one week",
        pet: "yes",
        pottingReq: "6'' pot"
},
{
    id: 9,
    name:"Marble Queen",
    img: "img/marble_queen.JPG",
    price: 70,
    size: "SM",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "medium to bright light would be ideal",
    waterReq: "1 x one week",
    pet: "no",
    pottingReq: "6'' pot"
},
{
    id: 10,
    name:"Air Plant",
    img: "img/air_plant.JPG",
    price: 30,
    size: "XS",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "bright light is recommended",
    waterReq: "1 x one week",
    pet: "no",
    pottingReq: "unpotted"
},
{
    id: 11,
    name:"Calathea",
    img: "img/calathea.JPG",
    price: 55,
    size: "SM",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "medium to bright light would be ideal",
    waterReq: "1 x one week",
    pet: "yes",
    pottingReq: "4'' pot"
},
{
    id: 12,
    name:"Alocasia",
    img: "img/alocasia.JPG",
    price: 55,
    size: "MD",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "bright light is recommended",
    waterReq: "1 x one week",
    pet: "no",
    pottingReq: "6'' pot"
}
]

export const detailProduct = {
    id:"5d0f72aa0f66b75f1b55960e",
    name:"Zebra Plant",
    img: "img/zebra_plant.JPG",
    price: 80,
    size: "xs",
    inCart: false,
    count: 3,
    total: 0,
    userID: "",
    lightReq: "bright",
    waterReq: "1 x three weeks",
    pet: "no",
    pottingReq: "3'' pot"
};